name: IC
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  testar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: angelonuffer/0
        ref: b9fc34a64624f4242980906ac8e5f987d87162fc
        path: "./0"
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - run: node 0/código/0_node.js testes/0